document.write(' <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">');
document.write('        <div class="carousel-indicators">');
document.write('            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>');
document.write('            <!--<button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>');
document.write('            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>-->');
document.write('        </div>');
document.write('        <div class="carousel-inner">');
document.write('            <div class="carousel-item active">');
document.write('                <img src="contents/gray.jpg" class="w-100" style="height: 500px;" alt="...">');
document.write('                <div class="carousel-caption" style="width: 100%;">');
document.write('                    <h3><strong><span style="color: white;">Comedk - 2023 Info</span></strong></h3><br>');
document.write('                    <h6>');
document.write('                        <strong>Mock Allotment Result : <span style="color: red;">2 PM, 14 July 2023</span></strong><br>');
document.write('                        Mock Round is a trial round hence you will not see any decision tabs <br>');
document.write('                        Provision to change / edit preferences in choice filling form <br><br>');
document.write('                        <strong>Starts From : <span style="color: red;">2 PM, 14 July 2023 to 3 PM, 16 July 2023</span></strong><br>');
document.write('                        <strong>First Round Allotment Result : <span style="color: red;">2PM, 18 July 2023</span></strong>');
document.write('                        <br><br>');
document.write('                        <strong>');
document.write('                            <span style="color: red;">FEE PAYMENT : </span>');
document.write('                            Payment Modes - Credit card, Debit Card or Net Banking Payments in installments/ or multiple transactions are not accepted');
document.write('                            TRANSACTION LIMIT IS DIFFERENT FROM BANK BALANCE. Please speak to your bank to understand the same.');
document.write('                            Candidates are advised not to wait till the last hour of decision making, to avoid payment failures. ');
document.write('                            Subsequent requests for extension of time will not be entertained.');
document.write('                        </strong><br><br>');
document.write('                        <strong>');
document.write('                            <span class="red">COLLEGE LOCATION : </span>');
document.write('                            Candidates are requested to check the LOCATION of the college they are interested in and');
document.write('                            ensure they choose the correct College code as per the location during choice filling. ');
document.write('                            <a class="red" href="pdf/2023/COMEDK_Engineering_Final_Seat_Availability_and_Fee_at_beginning_of_Round_1.pdf"> Click here </a>');
document.write('                            to check the location of the college and the college code.');
document.write('                        </strong>');
document.write('                    </h6>');
document.write('                </div>');
document.write('            </div>');
document.write('            <!--<div class="carousel-item">');
document.write('            <img src="contents/copy.png" class="w-100" style="height: 500px;" alt="...">');
document.write('            <div class="carousel-caption">');
document.write('              <h5>Second slide label</h5>');
document.write('              <p>Some representative placeholder content for the second slide.</p>');
document.write('            </div>');
document.write('          </div>');
document.write('          <div class="carousel-item">');
document.write('            <img src="contents/copy.png" class="w-100" style="height: 500px;" alt="...">');
document.write('            <div class="carousel-caption">');
document.write('              <h5>Third slide label</h5>');
document.write('              <p>Some representative placeholder content for the third slide.</p>');
document.write('            </div>');
document.write('          </div>-->');
document.write('        </div>');
document.write('        <!--<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"');
document.write('            data-bs-slide="prev">');
document.write('            <span class="carousel-control-prev-icon" aria-hidden="true"></span>');
document.write('            <span class="visually-hidden">Previous</span>');
document.write('        </button>');
document.write('        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"');
document.write('            data-bs-slide="next">');
document.write('            <span class="carousel-control-next-icon" aria-hidden="true"></span>');
document.write('            <span class="visually-hidden">Next</span>');
document.write('        </button>-->');
document.write('    </div>');
document.write('');
