document.write('<div class="container">');
document.write('    <footer class="py-3">');
document.write('      <h5>College Dosth Acadmey</h5>');
document.write('      <div class="row">');
document.write('        <div class="col-6 col-md-3 mb-3 text-dark">');
document.write('          <hr class="solid">');
document.write('          <a href="../rd/rd-index.html" class="nav-link p-0 text-dark">');
document.write('            <h6 class="text-decoration-underline">COMPETITIVE EXAM 2023</h6>');
document.write('          </a>');
document.write('          <ul class="nav flex-column">');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-23-jee-main.html" class="nav-link p-0 text-secondary">JEE-MAIN</a></li>');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-23-jee-adv.html" class="nav-link p-0 text-secondary">JEE-ADV</a></li>');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-23-neet.html" class="nav-link p-0 text-secondary">NEET</a></li>');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-23-kcet.html" class="nav-link p-0 text-secondary">UG-CET / KCET</a></li>');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-23-karpu.html" class="nav-link p-0 text-secondary">KARNATAKA PU BOARD</a></li>');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-23-comedk.html" class="nav-link p-0 text-secondary">COMEDK</a></li>');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-23-pessat.html" class="nav-link p-0 text-secondary">PESSAT</a></li>');
document.write('          </ul>');
document.write('        </div>');
document.write('        <div class="col-6 col-md-3 mb-3">');
document.write('          <hr class="solid">');
document.write('          <h6 class="text-decoration-underline">COMPETITIVE EXAM 2024</h6>');
document.write('          <ul class="nav flex-column">');
document.write('            <!--<li class="nav-item mb-2"><a href="../rd/rd-24-jee-main.html" class="nav-link p-0 text-secondary">JEE-MAIN</a></li>-->');
document.write('            <!--<li class="nav-item mb-2"><a href="../rd/rd-24-jee-adv.html" class="nav-link p-0 text-secondary">JEE-ADV</a></li>-->');
document.write('            <!--<li class="nav-item mb-2"><a href="../rd/rd-24-neet.html" class="nav-link p-0 text-secondary">NEET</a></li>-->');
document.write('            <!--<li class="nav-item mb-2"><a href="../rd/rd-24-kcet.html" class="nav-link p-0 text-secondary">UG-CET / KCET</a></li>-->');
document.write('            <li class="nav-item mb-2"><a href="../rd/rd-24-karpu.html" class="nav-link p-0 text-secondary">KARNATAKA PU BOARD</a></li>');
document.write('            <!--<li class="nav-item mb-2"><a href="../rd/rd-24-comedk.html" class="nav-link p-0 text-secondary">COMEDK</a></li>-->');
document.write('            <!--<li class="nav-item mb-2"><a href="../rd/rd-24-pessat.html" class="nav-link p-0 text-secondary">PESSAT</a></li>-->');
document.write('          </ul>');
document.write('        </div>');
document.write('        <div class="col-6 col-md-2 mb-3">');
document.write('          <ul class="nav flex-column">');
document.write('            <li class="nav-item mb-2"></li>');
document.write('          </ul>');
document.write('        </div>');
document.write('        <div class="col-6 col-md-3 mb-3">');
document.write('          <ul class="nav flex-column">');
document.write('            <li class="nav-item mb-2"></li>');
document.write('          </ul>');
document.write('        </div>');
document.write('      </div>');
document.write('');
document.write('      <div class="container bg-dark text-white">');
document.write('        <center>');
document.write('          <div id="demo"></div>');
document.write('        </center>');
document.write('      </div>');
document.write('      <div class="d-flex justify-content-between py-4 my-4 border-top">');
document.write('        <p>&copy; College Dosth Acadmey 2023, Inc. All rights reserved.</p><br><br>');
document.write('        <ul class="list-unstyled d-flex">');
document.write('          <a class="link-body-emphasis" href="https://www.instagram.com/college_dosth_academy/">');
document.write('            <i class="fa-brands fa-instagram fa-2xl" style="color: black;"></i>');
document.write('          </a>&nbsp;&nbsp;');
document.write('          <a class="link-body-emphasis" href="">');
document.write('            <i class="fa-brands fa-twitter fa-2xl" style="color: #000000;"></i>');
document.write('          </a>&nbsp;&nbsp;');
document.write('        </ul>');
document.write('      </div>');
document.write('       <div class="container-xxl bg-dark text-white"><center><h6>Version 2.1.5</h6></center></div>');
document.write('    </footer>');
document.write('  </div>');
