document.write('<!-- Meta Signs -->');
document.write('  <meta charset="UTF-8">');
document.write('  <meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('');
document.write('  <!-- Title Icon --->');
document.write('  <title>College Dosth Acadmey</title>');
document.write('  <link rel="shortcut icon" href="contents/Logo.png">');
document.write('');
document.write('  <!-- Latest compiled and minified CSS -->');
document.write('  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">');
document.write('');
document.write('  <!-- jQuery library -->');
document.write('  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.slim.min.js"></script>');
document.write('');
document.write('  <!-- Popper JS -->');
document.write('  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>');
document.write('');
document.write('  <!-- Latest compiled JavaScript -->');
document.write('  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>');
document.write('');
document.write('  <!-- Box Icons Links -->');
document.write('  <script src="https://kit.fontawesome.com/89b3df4f3f.js" crossorigin="anonymous"></script>');
