document.write('<!-- Meta Signs -->');
document.write('  <meta charset="UTF-8">');
document.write('  <meta http-equiv="X-UA-Compatible" content="IE=edge">');
document.write('  <meta name="viewport" content="width=device-width, initial-scale=1.0">');
document.write('  <!-- Title Icon --->');
document.write('  <title>College Dosth Acadmey</title>');
document.write('  <link rel="shortcut icon" href="contents/Logo.png">');
document.write('  <!-- Latest compiled and minified CSS -->');
document.write('  <link href="css/bootstrap.min.css" rel="stylesheet">');
document.write('  <!-- Latest compiled JavaScript -->');
document.write('  <script src="js/bootstrap.bundle.min.js"></script>');
document.write('  <!-- Box Icons Links -->');
document.write('  <script src="https://kit.fontawesome.com/89b3df4f3f.js" crossorigin="anonymous"></script>');
