document.write('<div class="contanier bg-white justify-content-center mt-1">');
document.write('    <marquee behavior="sliding" direction="left" scrollamount="10">');
document.write('      <h4>');
document.write('        <strong>');
document.write('          <a href="" style="color: red;"></a>');
document.write('          <br>');
document.write('          <a href="" style="color: red;"></a>');
document.write('        </strong>');
document.write('      </h4>');
document.write('    </marquee>');
document.write('  </div>');
document.write('<div class="container-lg">');
document.write('<div class="alert alert-success alert-dismissible fade show">');
document.write('  <button type="button" class="btn-close" data-bs-dismiss="alert"></button>');
document.write('');
document.write('<strong>&bull;&nbsp;</strong>IMPORTANT NOTE FOR CHOICE FILLING');
document.write('<br>');
document.write('1) Click on Choice Filling tab, then click on "Click here to view Choice Filling Form" to enter your preference for "Mock" Choice filling');
document.write('<br>');
document.write('2) Choice filling tab for Mock Round is available from 11am, 11 JULY to 5pm, 12 JULY');
document.write('<br>');
document.write('3) Candidates can add as many preferences as they wish as per college or as per course');
document.write('<br>');
document.write('4) Candidate can modify their college/courses selected any number of times');
document.write('<br>');
document.write('5) Candidates can edit their preferences till the last date of choice filling');
document.write('<br>');
document.write('6) Only the “Saved” preferences will be considered');
document.write('</div>');
document.write('</div>');