document.write('<div class="contanier bg-white justify-content-center mt-1">');
document.write('<marquee behavior="sliding" direction="left" scrollamount="10">');
document.write('<h4>');
document.write('<strong>&bull;&nbsp;');
document.write('<a href="" style="color: red;">Comedk - 2023 Round 2 Phase 2 Cut off Ranks after Engineering Allotment </a>');
document.write('</strong>');
document.write('</h4>');
document.write('</marquee>');
document.write('<marquee behavior="sliding" direction="left" scrollamount="10">');
document.write('<h4>');
document.write('<strong>&bull;&nbsp;');
document.write('<a href="" style="color: red;">Comedk - 2023 Engineering Vacant Seats After Round 2 Phase 2 Allotment</a>');
document.write('</strong>');
document.write('</h4>');
document.write('</marquee>');
document.write('</div>');
document.write('<div class="container">');
document.write('<div class="shadow-lg p-1 bg-dark text-white rounded-lg">');
document.write('<h2>');
document.write('<center>');
document.write('COLLEGE DOSTH ACADMEY');
document.write('</center>');
document.write('</h2>');
document.write('</div>');
document.write('</div>');
document.write('<br>');
document.write('');