
document.write('<nav class="navbar navbar-dark bg-dark" aria-label="First navbar example">');
document.write('    <div class="container-fluid">');
document.write('      <a class="navbar-brand" href="../rd/rd-index.html">COLLEGE DOSTH ACADMEY</a>');
document.write('      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample01"');
document.write('        aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">');
document.write('        <span class="navbar-toggler-icon"></span>');
document.write('      </button>');
document.write('      <div class="collapse navbar-collapse" id="navbarsExample01">');
document.write('        <ul class="navbar-nav me-auto mb-2">');
document.write('          <li class="nav-item">');
document.write('            <a class="nav-link active" aria-current="page" href="../rd/rd-index.html">Home</a>');
document.write('          </li>');
document.write('          <li class="nav-item dropdown">');
document.write('            <a class="nav-link dropdown-toggle" href="../rd/rd-23-ce.html" data-bs-toggle="dropdown"');
document.write('              aria-expanded="false">COMPETITIVE EXAM 2023</a>');
document.write('            <ul class="dropdown-menu">');
document.write('              <li><a class="dropdown-item" href="../rd/rd-23-jee-main.html">JEE-MAIN</a></li>');
document.write('              <li><a class="dropdown-item" href="../rd/rd-23-jee-adv.html">JEE-ADV</a></li>');
document.write('              <li><a class="dropdown-item" href="../rd/rd-23-neet.html">NEET</a></li>');
document.write('              <li><a class="dropdown-item" href="../rd/rd-23-kcet.html">UG-CET / KCET</a></li>');
document.write('              <li><a class="dropdown-item" href="../rd/rd-23-karpu.html">KARNATAKA PU BOARD</a></li>');
document.write('              <li><a class="dropdown-item" href="../rd/rd-23-comedk.html">COMEDK</a></li>');
document.write('              <li><a class="dropdown-item" href="../rd/rd-23-pessat.html">PESSAT</a></li>');
document.write('            </ul>');
document.write('          </li>');
document.write('          <li class="nav-item dropdown">');
document.write('            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown"');
document.write('              aria-expanded="false">COMPETITIVE EXAM 2024</a>');
document.write('            <ul class="dropdown-menu">');
document.write('              <li><a class="dropdown-item disabled " href="../rd/rd-24-jee-main.html">JEE-MAIN</a></li>');
document.write('              <li><a class="dropdown-item disabled " href="../rd/rd-24-jee-adv.html">JEE-ADV</a></li>');
document.write('              <li><a class="dropdown-item disabled " href="../rd/rd-24-neet.html">NEET</a></li>');
document.write('              <li><a class="dropdown-item disabled " href="../rd/rd-24-kcet.html">UG-CET / KCET</a></li>');
document.write('              <li><a class="dropdown-item" href="../rd/rd-24-karpu.html">KARNATAKA PU BOARD</a></li>');
document.write('              <li><a class="dropdown-item disabled " href="../rd/rd-24-comedk.html">COMEDK</a></li>');
document.write('              <li><a class="dropdown-item disabled " href="../rd/rd-24-pessat.html">PESSAT</a></li>');
document.write('            </ul>');
document.write('          </li>');
document.write('          <li class="nav-item">');
document.write('            <a class="nav-link" aria-current="page" href="contact.us.html">Contact Us</a>');
document.write('          </li>');
document.write('        </ul>');
document.write('      </div>');
document.write('    </div>');
document.write('  </nav>');
